version: "3"
services:
  pgstac:
    container_name: pgstac
    image: pgstac
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
    ports:
      - "5439:5432"
    volumes:
      - pgstac-pgdata:/var/lib/postgresql/data
      - ./src:/opt/src
      - ./scripts/bin:/opt/bin
volumes:
  pgstac-pgdata:
